### PR TITLE
[fuel-core] Add Response validator to ExecutionOption

### LINKED ISSUE #379: API Request: graceful handling of 304
Linking the old ticket #191,

When using `Fuel` and setting `If-None-Match` manually, when the server returns a 304, currently an `HttpException` is raised, whereas this is actually expected. The happy-path shouldn't be "exceptional". When a 204 (No Content) is returned, Fuel doesn't complain unless you try to deserialize. 

As it stands, by default `redirectResponseInterceptor` will not match the 304 (which is correct), followed by the `validatorResponseInterceptor` will error as it's not included in the default `validRange`. Only the 200-299 range is handled as valid, whereas 100-399 should be considered valid; only 400-599 are error codes.
https://github.com/kittinunf/Fuel/blob/56cf7ce2af6ea39b2fb013564d188a812c42cf55/fuel/src/main/kotlin/com/github/kittinunf/fuel/core/FuelManager.kt#L58

The default should not indicate something is an error when it's not (304, 300, 103, ...).
RxJS used to have the same issue, but this was fixed: https://github.com/ReactiveX/rxjs/issues/3308

### PR DESCRIPTION
**Pull request by kittinunf**
## Description

This PR aims to fix #379. Invalidate usage of `validatorResponseInterceptor` and introducing the `responseValidator` in the `ExecutionOptions` instead. 

### Usage 
It should be pretty straightforward. The default implementation is to check whether it is fallen into 4xx-5xx or not, if yes then it will be considered failure. And it could be overridden just like other things in `RequestExecutionOptions` .

## Type of change

Check all that apply

- [x] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Refactoring (a change which changes the current internal or external interface)
- [ ] This change requires a documentation update

## How Has This Been Tested?

In case you did not include tests describe why you and how you have verified the
changes, with instructions so we can reproduce. If you have added comprehensive
tests for your changes, you may omit this section.

## Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation, if necessary
- [x] My changes generate no new compiler warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Inspect the bytecode viewer, including reasoning why

### CODE REVIEW

**Comment by kittinunf** [comment]
@SleeplessByte Can you please help check whether it is a good direction to go? Maybe I misunderstand something ...

File: fuel/src/main/kotlin/com/github/kittinunf/fuel/core/requests/DefaultRequest.kt [hunk 1]
```diff
@@ -198,8 +199,8 @@ data class DefaultRequest(
      */
     override fun body(openStream: BodySource, calculateLength: BodyLength?, charset: Charset, repeatable: Boolean): Request {
         _body = DefaultBody
-            .from(openStream = openStream, calculateLength = calculateLength, charset = charset)
-            .let { body -> if (repeatable) body.asRepeatable() else body }
+                .from(openStream = openStream, calculateLength = calculateLength, charset = charset)
```
Comment (SleeplessByte) [inline fuel/src/main/kotlin/com/github/kittinunf/fuel/core/requests/DefaultRequest.kt]: You probably didn't want to change this indentation to 8 instead of 4.

File: fuel/src/main/kotlin/com/github/kittinunf/fuel/core/requests/DefaultRequest.kt [hunk 2]
```diff
@@ -217,7 +218,7 @@ data class DefaultRequest(
      * @return [Request] the request
      */
     override fun body(stream: InputStream, calculateLength: BodyLength?, charset: Charset, repeatable: Boolean) =
-        body(openStream = { stream }, calculateLength = calculateLength, charset = charset, repeatable = repeatable)
+            body(openStream = { stream }, calculateLength = calculateLength, charset = charset, repeatable = repeatable)
```
Comment (SleeplessByte) [inline fuel/src/main/kotlin/com/github/kittinunf/fuel/core/requests/DefaultRequest.kt]: You probably didn't want to change this indentation to 8 instead of 4.

File: fuel/src/main/kotlin/com/github/kittinunf/fuel/core/requests/DefaultRequest.kt [hunk 3]
```diff
@@ -227,7 +228,7 @@ data class DefaultRequest(
      * @return [Request] the request
      */
     override fun body(bytes: ByteArray, charset: Charset) =
-        body(stream = ByteArrayInputStream(bytes), calculateLength = { bytes.size.toLong() }, charset = charset, repeatable = true)
+            body(stream = ByteArrayInputStream(bytes), calculateLength = { bytes.size.toLong() }, charset = charset, repeatable = true)
```
Comment (SleeplessByte) [inline fuel/src/main/kotlin/com/github/kittinunf/fuel/core/requests/DefaultRequest.kt]: You probably didn't want to change this indentation to 8 instead of 4.

File: fuel/src/main/kotlin/com/github/kittinunf/fuel/core/requests/DefaultRequest.kt [hunk 4]
```diff
@@ -237,13 +238,13 @@ data class DefaultRequest(
...
      */
     override fun body(body: String, charset: Charset): Request =
-        body(bytes = body.toByteArray(charset), charset = charset)
-            .let {
-                if (header(Headers.CONTENT_TYPE).lastOrNull().isNullOrBlank())
-                    header(Headers.CONTENT_TYPE, "text/plain; charset=${charset.name()}")
-                else
-                    it
-            }
+            body(bytes = body.toByteArray(charset), charset = charset)
```
Comment (SleeplessByte) [inline fuel/src/main/kotlin/com/github/kittinunf/fuel/core/requests/DefaultRequest.kt]: You probably didn't want to change this indentation to 8 instead of 4.

File: fuel/src/main/kotlin/com/github/kittinunf/fuel/core/requests/DefaultRequest.kt [hunk 5]
```diff
@@ -392,45 +406,62 @@ data class DefaultRequest(
     }
 
     override fun response(handler: ResponseResultHandler<ByteArray>) =
-        response(ByteArrayDeserializer(), handler)
+            response(ByteArrayDeserializer(), handler)
```
Comment (SleeplessByte) [inline fuel/src/main/kotlin/com/github/kittinunf/fuel/core/requests/DefaultRequest.kt]: You probably didn't want to change this indentation to 8 instead of 4.

Here and below.

File: fuel/src/main/kotlin/com/github/kittinunf/fuel/core/requests/DefaultRequest.kt (hunk 1 above)
Comment (kittinunf) [reply fuel/src/main/kotlin/com/github/kittinunf/fuel/core/requests/DefaultRequest.kt]: I think we need to sync on this! Can you share your setting and push to the project?

File: fuel/src/main/kotlin/com/github/kittinunf/fuel/core/requests/DefaultRequest.kt (hunk 2 above)
Comment (kittinunf) [reply fuel/src/main/kotlin/com/github/kittinunf/fuel/core/requests/DefaultRequest.kt]: Roger that

File: fuel/src/main/kotlin/com/github/kittinunf/fuel/core/FuelManager.kt [hunk 6]
```diff
@@ -65,7 +64,7 @@ class FuelManager : RequestFactory, RequestFactory.Convenience {
     private val requestInterceptors: MutableList<FoldableRequestInterceptor> =
             mutableListOf(ParameterEncoder)
     private val responseInterceptors: MutableList<FoldableResponseInterceptor> =
-            mutableListOf(redirectResponseInterceptor(this), validatorResponseInterceptor(200..299))
```
Comment (kittinunf) [inline fuel/src/main/kotlin/com/github/kittinunf/fuel/core/FuelManager.kt]: I don't feel like using `validatorResponseInterceptor` is a good use of Interceptor anymore. I think I will just take this opportunity and remove it without effect users' behaviors.

Comment (iNoles) [reply fuel/src/main/kotlin/com/github/kittinunf/fuel/core/FuelManager.kt]: range from 200 to 299 can be difficult if there is more http status code that considered to be okay.

Comment (kittinunf) [reply fuel/src/main/kotlin/com/github/kittinunf/fuel/core/FuelManager.kt]: Yeah, agree. After this PR is merged, `!(response.isServerError || response.isClientError)` is the new logic, so it should be okay.

File: fuel/src/main/kotlin/com/github/kittinunf/fuel/core/requests/DefaultRequest.kt (hunk 1 above)
Comment (SleeplessByte) [reply fuel/src/main/kotlin/com/github/kittinunf/fuel/core/requests/DefaultRequest.kt]: Yes, but I think I just followed the klint instructions. I think the contributors file also has a few lines on how to get editorconfig working.

File: fuel/src/main/kotlin/com/github/kittinunf/fuel/core/RequestExecutionOptions.kt [hunk 7]
```diff
@@ -29,6 +31,9 @@ data class RequestExecutionOptions(
     var allowRedirects: Boolean? = null
     var useHttpCache: Boolean? = null
     var interruptCallbacks: MutableCollection<InterruptCallback> = mutableListOf()
+    var responseValidator: ResponseValidator = { response ->
+        !(response.isServerError || response.isClientError)
```
Comment (kittinunf) [inline fuel/src/main/kotlin/com/github/kittinunf/fuel/core/RequestExecutionOptions.kt]: This should allow 3xx as a Success in the `Result` value.

**Comment by kittinunf** [comment]
@SleeplessByte Happy new year bro 🎉 

One more check when possible! 🙏

**Comment by kittinunf** [comment]
Shall we merge this? If anyone can review? 🙏

File: fuel/src/main/kotlin/com/github/kittinunf/fuel/core/RequestExecutionOptions.kt (hunk 7 above)
Comment (SleeplessByte) [reply fuel/src/main/kotlin/com/github/kittinunf/fuel/core/RequestExecutionOptions.kt]: Haha, did you review yourself 💯

**Comment by SleeplessByte** [comment]
The only question I have left @kittinunf , is what happens in this case:

```
val request = Fuel.get(url)
request['If-None-Match'] = 'some etag'

val response = request.responseObject(...)
// This will be fine if the etag doesn't match (the resource has changed) and you get a 200 or the like

// What happens if it DOES match and you get a 304? 
// - Do we throw? 
// - Could we return an empty body -- is there a nice way we can handle that?
// - Do we need a new API that basically tells you if you got "responseWithBodyOfType, responseWithoutBody"?
```

**Comment by kittinunf** [comment]
Let's write a test for that ⬆️ 🙃

**Comment by SleeplessByte** [comment]
🤗

**Comment by kittinunf** [comment]
@SleeplessByte Can we defer the abovementioned for later fix? So that we can merge this and release 2.0

**Comment by SleeplessByte** [comment]
@kittinunf sure, just open up an issue, and then merge. Put it in the release notes :)

**Comment by kittinunf** [comment]
@SleeplessByte yeah, I created here #578. Can you approve this if there is no more concern aside from that?
