### PR TITLE
Fix Jackson extension functions and their tests

### LINKED ISSUE #775: Jackson extensions: responseObject() should return CancellableRequest object
Some [`responseObject(...)`](https://github.com/kittinunf/fuel/blob/63c5f4c/fuel-jackson/src/main/kotlin/com/github/kittinunf/fuel/jackson/FuelJackson.kt#L20-L26) extension methods for Jackson don't expose result of `CancellableRequest` type, which makes them inconsistent with other helper methods and limits their use cases for no reason (e.g. no way to `cancel()` or `join()` request when these shorthand methods used).

Specifically, shorthand methods that accept the triple of _request_, _response_ and _result_ have `Unit` return type.

### PR DESCRIPTION
**Pull request by detouched**
This fixes the tests of Jackson extension functions for asynchronous requests (#776). These tests were silently failing for a long time because of the assertions in the callbacks which are async and not visible to the test engine. As a result, the tests became out of date, so aside from ensuring the assertions are now able to fail the tests this PR also contains a decent amount of changes in the setup procedures as well as assertions themselves.

Assertions are now ensured to take an effect on the test outcome by explicitly awaiting on the `CancellableRequest` object which is returned by the extension functions using the `get()` method inherited from `Future<Response>`.
This change also fixes two extension functions that did not return `CancellableRequest` object for no reason (#775).

I also fixed code formatting around the lines I touched according to what seems to be the most common in this project.

Fixes #775 and #776.

## Type of change

- [x] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Refactoring (a change which changes the current internal or external interface)
- [ ] This change requires a documentation update

## How Has This Been Tested?

I did not include any new tests for the change in the production code (#775) 
because existing tests do verify that change after the fix of #776.

## Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas **(n/a)**
- [x] I have made corresponding changes to the documentation, if necessary
- [x] My changes generate no new compiler warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Inspect the bytecode viewer, including reasoning why **(n/a)**

### CODE REVIEW

File: fuel-jackson/src/test/kotlin/com/github/kittinunf/fuel/FuelJacksonTest.kt [hunk 1]
```diff
@@ -38,25 +40,33 @@ class FuelJacksonTest : MockHttpTestCase() {
...
-                assertThat(result.component1(), instanceOf(HttpBinUserAgentModel::class.java))
-                assertThat(result.component1()?.userAgent, not(""))
-                assertThat(result.component2(), instanceOf(FuelError::class.java))
+                assertThat(result, instanceOf(Result.Success::class.java))
+                with(result as Result.Success) {
+                    assertThat(value, instanceOf(HttpBinUserAgentModel::class.java))
+                    assertThat(value.userAgent, not(""))
+                }
             }
+            .get()
```
Comment (detouched) [inline fuel-jackson/src/test/kotlin/com/github/kittinunf/fuel/FuelJacksonTest.kt:49]: This ensures that assertions in the asynchronous callback are able to fail the tests.

**Review by SleeplessByte — APPROVED** [review]
Looks like this fixes the issue!

**Comment by kittinunf** [comment]
This is amazinggg! Thanks!

**Review by kittinunf — APPROVED** [review]
