### PR TITLE
Replace Content-Type when jsonBody is called

### LINKED ISSUE #473: jsonBody does not replace default content encoding
# Bug Report

## Description
when POST-ing a json body the generated request contains both of these headers
```
Content-Type : application/x-www-form-urlencoded
content-type : application/json
```

because of https://github.com/kittinunf/Fuel/blob/master/fuel/src/main/kotlin/com/github/kittinunf/fuel/core/Request.kt#L149

## To Reproduce

```Kotlin
val curl = Fuel.post("https://someurl.com")
            .jsonBody(body = "{}")
            .cUrlString()
println(curl)
```

## Expected behavior
the POST request should have only one Content-Type

### PR DESCRIPTION
**Pull request by NikkyAI**
## Description

Ensures that the default Content-Type of the request gets replaced instead of appending to the list or adding to a different header when `jsonBody` is called.

eventually case insensitive headers might be useful

Fixes #473

## Type of change

Check all that apply

- [x] Bug fix (a non-breaking change which fixes an issue)

## How Has This Been Tested?

In case you did not include tests describe why you and how you have verified the
changes, with instructions so we can reproduce. If you have added comprehensive
tests for your changes, you may omit this section.

## Checklist:

- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by SleeplessByte** [comment]
This is a patch that will work, and as you already note headers **SHOULD** be normalised (and thus are case-insensitive).

I'm okay with merging this, but let's keep track of this issue and actually fix it down the line :)

**Comment by SleeplessByte** [comment]
@NikkyAI if you want, could you add a test that FAILS with the old behaviour and PASSES with the new behaviour?

File: fuel/src/main/kotlin/com/github/kittinunf/fuel/core/Request.kt [hunk 1]
```diff
@@ -146,7 +146,7 @@ class Request(
     fun body(body: String, charset: Charset = Charsets.UTF_8): Request = body(body.toByteArray(charset))
 
     fun jsonBody(body: String, charset: Charset = Charsets.UTF_8): Request {
-        header("content-type" to "application/json")
+        headers["Content-Type"] = "application/json"
         return body(body, charset)
     }
```
Comment (markGilchrist) [inline fuel/src/main/kotlin/com/github/kittinunf/fuel/core/Request.kt]: should we amend the test for this `RequestTest.kt` line 301, currently the test passes and if it is a bug the test should also be changed to reflect the desired behaviour

**Comment by SleeplessByte** [comment]
Seems to revert the constants stuff @NikkyAI

**Comment by NikkyAI** [comment]
oops

File: fuel/src/main/kotlin/com/github/kittinunf/fuel/core/Request.kt (hunk 1 above)
Comment (kittinunf) [reply fuel/src/main/kotlin/com/github/kittinunf/fuel/core/Request.kt]: Agree with that. So we have test that covered the behavior.

**Comment by markGilchrist** [comment]
@kittinunf  @NikkyAI  have you updated the tests?

**Comment by NikkyAI** [comment]
i was not aware there were tests to update or fix
.. and i am not sure how most of them work :/

**Comment by markGilchrist** [comment]
@NikkyAI  if you `cmd` click on the function it will show you where it is called (Mac + Android Studio)

RequestTest.kt, line 301, I am guessing you need to update line 308

**Comment by NikkyAI** [comment]
the tests currently fail already when there is mutliple fields in "Content-Type" the only thing left to cehck if someone accidentally used multiple different casings for the content-type header

**Comment by NikkyAI** [comment]
Just tested this, the test also fails when there is expected/different content-type header with different casing
since the list of header will be different the test will catch it

since that seems safe, i think its ready to merge ?
