### PR TITLE
Fixed and Improved Coverage of Moshi

### LINKED ISSUE #433: Moshi Kotlin
KotlinJsonAdapterFactory() uses the Kotlin Reflection Library that will increases APK Sizes because it is 2.5 MB jar files to be added to the project. The Moshi's Kotlin codegen uses kapt.  The Performance wouldn't be great as codegen is. 

My opinion to be avoid of the kotlin-reflect dependency. One more thing, the latest version of moshi is 1.6.0.

### PR DESCRIPTION
**Pull request by iNoles**
Thank you for submitting your Pull Request. Please make sure you have
familiarised yourself with the [Contributing Guidelines](https://github.com/kittunf/Fuel/CONTRIBUTING.md)
before continuing.

## Description

This will fixed three problems that found in Issue number 433. This is also improved test coverage of Moshi too. Also, I updated the moshi version to 1.6.0.

Fixes #433 

## Type of change

Check all that apply

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Refactoring (change which changes the current internal or external interface)
- [ ] This change requires a documentation update

## How Has This Been Tested?

In case you did not include tests describe why you and how you have verified the
changes, with instructions so we can reproduce. If you have added comprehensive
tests for your changes, you may ommit this section.

## Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation, if necessary
- [x] My changes generate no new compiler warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: fuel-moshi/src/main/kotlin/com/github/kittinunf/fuel/moshi/FuelMoshi.kt [hunk 1]
```diff
@@ -1,22 +1,25 @@
...
+inline fun <reified T : Any> Request.responseObject() = response(moshiDeserializerOf(T::class))
 
-inline fun <reified T : Any> moshiDeserializerOf() = object : ResponseDeserializable<T> {
-    override fun deserialize(content: String): T? =
-            Moshi.Builder()
-                    .add(KotlinJsonAdapterFactory())
-                    .build()
-                    .adapter(T::class.java)
-                    .fromJson(content)
+fun <T : Any> moshiDeserializerOf(kClass: KClass<T>) = object : ResponseDeserializable<T> {
```
Comment (kittinunf) [inline fuel-moshi/src/main/kotlin/com/github/kittinunf/fuel/moshi/FuelMoshi.kt]: [Q] What is the benefit of this version compared to the original version with usage of `reified` and `::class.java` ?

```
inline fun <reified T : Any> moshiDeserializerOf() = object : ResponseDeserializable<T> {
  override fun deserialize(content: String): T? = Moshi.Builder().build().adapter(T::class.java).fromJson(content) 
}
```
?

File: fuel-moshi/src/test/kotlin/com/github/kittinunf/fuel/FuelMoshiTest.kt [hunk 2]
```diff
@@ -29,7 +29,7 @@ class FuelMoshiTest {
     @Test
     fun moshiTestResponseObject() {
         Fuel.get("/user-agent")
-                .responseObject(moshiDeserializerOf<HttpBinUserAgentModel>()) { _, _, result ->
+                .responseObject(moshiDeserializerOf(HttpBinUserAgentModel::class)) { _, _, result ->
```
Comment (kittinunf) [inline fuel-moshi/src/test/kotlin/com/github/kittinunf/fuel/FuelMoshiTest.kt]: I feel like `moshiDeserializerOf<HttpBinUserAgentModel>()` triumphs `moshiDeserializerOf(HttpBinUserAgentModel::class)` (at very least, it is less keystroke). What do you think about it?

File: fuel-moshi/src/main/kotlin/com/github/kittinunf/fuel/moshi/FuelMoshi.kt (hunk 1 above)
Comment (iNoles) [reply fuel-moshi/src/main/kotlin/com/github/kittinunf/fuel/moshi/FuelMoshi.kt]: @kittinunf, the original version is quite sucks when you looked at the bytecode level because you get FOUR Classes for this single files.
Mine version is quite Smaller than the original version.

File: fuel-moshi/src/test/kotlin/com/github/kittinunf/fuel/FuelMoshiTest.kt (hunk 2 above)
Comment (iNoles) [reply fuel-moshi/src/test/kotlin/com/github/kittinunf/fuel/FuelMoshiTest.kt]: This is one of the Trade-Off from fixing the moshiDeserializerOf() function.

File: fuel-moshi/src/main/kotlin/com/github/kittinunf/fuel/moshi/FuelMoshi.kt (hunk 1 above)
Comment (kittinunf) [reply fuel-moshi/src/main/kotlin/com/github/kittinunf/fuel/moshi/FuelMoshi.kt]: Ok then, should we also use the javaClass version so that we can avoid use the `kotlin.KClass` directly?

``` Kotlin
fun <T : Any> moshiDeserializerOf(clazz: Class<T>)
```

File: fuel-moshi/src/test/kotlin/com/github/kittinunf/fuel/FuelMoshiTest.kt (hunk 2 above)
Comment (kittinunf) [reply fuel-moshi/src/test/kotlin/com/github/kittinunf/fuel/FuelMoshiTest.kt]: OK understood

**Comment by kittinunf** [comment]
I think this looks good as I don't have more concerns but more like a question.

File: fuel-moshi/src/main/kotlin/com/github/kittinunf/fuel/moshi/FuelMoshi.kt (hunk 1 above)
Comment (iNoles) [reply fuel-moshi/src/main/kotlin/com/github/kittinunf/fuel/moshi/FuelMoshi.kt]: Oh Okay I can do that.

**Comment by kittinunf** [comment]
Awesome!
